version: '3.8'

services:
  # 后端API服务
  backend:
    build: ./backend
    container_name: easycook-backend
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend/app.db:/app/app.db
      - ./logs/backend:/app/logs
    networks:
      - easycook-network

  # 前端Web服务
  frontend:
    build: ./frontend
    container_name: easycook-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - API_URL=${API_URL}
    volumes:
      - ./logs/frontend:/var/log/nginx
    networks:
      - easycook-network

  # Nginx反向代理
  nginx:
    image: nginx:stable-alpine
    container_name: easycook-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend/dist:/var/www/burning233.top/html
      - ./logs/nginx:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - easycook-network

  # Certbot容器用于SSL证书
  certbot:
    image: certbot/certbot
    container_name: easycook-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  easycook-network:
    driver: bridge

volumes:
  db-data:
  logs:
  certbot-conf:
  certbot-www: